apiVersion: mcp.caas.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: caas-eks
  namespace: default
spec:
  parameters:
    organizationName: upbound
    configuration: caas-eks
  writeConnectionSecretToRef:
    name: mcp-caas-eks-kubeconfig
