apiVersion: aws.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: gitops-master
  namespace: default
spec:
  parameters:
    id: gitops-master
    region: us-west-2
    version: "1.27"
    nodes:
      count: 3
      size: small
    serviceSelector: gitops-master
    gitops:
      kubeConfigSecretRef:
        name: mcp-caas-eks-kubeconfig
        namespace: default
  writeConnectionSecretToRef:
    name: gitops-master-kubeconfig
